# Generated by Django 3.0.7 on 2020-08-03 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_booking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingI',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.IntegerField(default=0)),
                ('type', models.CharField(default='', max_length=20)),
                ('book_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pathtk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_name', models.CharField(max_length=100)),
                ('spot_time', models.CharField(max_length=100)),
                ('spot_distance', models.IntegerField(default=0)),
                ('pref_no', models.IntegerField(default=0)),
                ('last_spot', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.RemoveField(
            model_name='busi',
            name='dest_count',
        ),
        migrations.RemoveField(
            model_name='busi',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='busi',
            name='path',
        ),
        migrations.RemoveField(
            model_name='busi',
            name='timings',
        ),
        migrations.AddField(
            model_name='pathtk',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.BusI'),
        ),
        migrations.AddField(
            model_name='pathtk',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.City'),
        ),
        migrations.AddField(
            model_name='pathtk',
            name='state_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.State'),
        ),
        migrations.AddField(
            model_name='bookingi',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.BusI'),
        ),
        migrations.AddField(
            model_name='bookingi',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Customer'),
        ),
    ]
