# Generated by Django 3.0.7 on 2020-08-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200803_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingi',
            name='froml',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingi',
            name='tol',
            field=models.CharField(default='', max_length=100),
        ),
    ]
