# Generated by Django 3.0.7 on 2020-08-07 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200805_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.City'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.State'),
        ),
        migrations.AddField(
            model_name='customer',
            name='village_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Pathtk'),
        ),
    ]
