# Generated by Django 3.0.7 on 2020-08-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200807_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='village_name',
        ),
    ]
