# Generated by Django 3.0.7 on 2020-08-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_customer_village_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingi',
            name='book_date',
            field=models.DateTimeField(),
        ),
    ]
