# Generated by Django 3.0.7 on 2020-08-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20200808_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingI',
            new_name='Bookings',
        ),
    ]
